### ISSUE TITLE
Copying mode does not work 100% of the time

### ISSUE THREAD

**Issue by fpg1503** [fpg1503/MakeXcodeGr8Again#1]

**Comment by Viniciuscarvalho** [comment]
@fpg1503 nesse register, tem como passar o `NSFileManager` também?

```
class DragView: NSView {
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        register(forDraggedTypes: [NSFilenamesPboardType, NSURLPboardType])
    }
```

**Comment by fpg1503** [comment]
Não, aí é um array de `String` com identifiers pros tipos que aceita, na verdade como é Swift 3 nem chama mais `NSFileManager`, chama só `FileManager`, inclusive isso pode estar causando problemas (por ser novo e beta).

**Comment by Viniciuscarvalho** [comment]
Então fazendo da maneira lá do YOLO não tem como corrigir esse problema do FileManager?

**Comment by fpg1503** [comment]
A maneira YOLO pula o processo de cópia e faz a modificação direto no .app que você arrasta então não está sujeita à falhas na cópia.

**Comment by fpg1503** [comment]
I think it has been fixed. If anyone has this issue again feel free to reopen it.
