### ISSUE TITLE
App submission 

### ISSUE THREAD

**Issue by meoz** [fpg1503/MakeXcodeGr8Again#14]
Just a question here. Since unsigning XCode comes with the implication that one could submit an app with ghosts, dragons and other nasty stuff. Wouldn't it be possible to just unsign in regular mode and use the unsigned mode for development with all its plugin-goodness and when ready to submit use the original signed version to upload the final binary to the App Store? 

Like this we can have it both ways, or am I overseeing something here?

**Comment by pvinis** [comment]
i guess thats why it makes a copy.. so you could use the `gr8` xcode for dev, and the regular xcode for uploading etc.

**Comment by fpg1503** [comment]
@meoz: @pvinis is right, that's my recommendation: never use anything but the regular Xcode to upload builds. I'd like to add a plugin to disable submissions (#4) so everyone must use the unmodified version of Xcode for that matter.
