### ISSUE TITLE
Unsigned XcodeGr8 app spinning beachball wo/any plugins

### ISSUE THREAD

**Issue by airzozo** [fpg1503/MakeXcodeGr8Again#19]
I have the signed and unsigned app.  The unsigned app will spin when an attempt is made to edit a file.  I have no plugins (although when I do, it works).

Oct  3 16:59:40 com.apple.xpc.launchd[1](com.apple.xpc.launchd.domain.user.503): Attempt to re-bootstrap service from different path, will use existing: service = com.apple.CoreSimulator.CoreSimulatorService, existing = /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc, conflicting = /Applications/XcodeGr8.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc

**Comment by littlepig10** [comment]
Check activity monitor. Is tccd using tons of CPU when Xcode was responding slowly?

**Comment by airzozo** [comment]
I cannot make it spin again.  I suspect it was the update to 10.12.  But, tccd is definitely hogging the CPU.  I have not upgraded to the latest Xcode8 or macOS because I don't want to upset my system which is still running Xcode 7 for compatibility.  Any ideas?

**Comment by fpg1503** [comment]
This issue will be closed because there hasn't been any activity for a few months. Feel free to [open a new one](https://github.com/fpg1503/MakeXcodeGr8Again/issues/newa) if you still experience this problem 👍
