### ISSUE TITLE
Crash on macOS Sierra

### ISSUE THREAD

**Issue by 651893553** [fpg1503/MakeXcodeGr8Again#20]
MAC OS 10.12 open project will crash, what's the solution?

**Comment by fpg1503** [comment]
Can you paste the crash info?

**Comment by fpg1503** [comment]
This issue will be closed because there hasn't been any activity for a few months. Feel free to [open a new one](https://github.com/fpg1503/MakeXcodeGr8Again/issues/newa) if you still experience this problem 👍
