### ISSUE TITLE
Add you to my RSS feed?

### ISSUE THREAD

**Issue by MKGitHub** [fpg1503/MakeXcodeGr8Again#21]
Hi,
I would like to add "MakeXcodeGr8Again" to my RSS feed – is that okay?
https://github.com/MKGitHub/TheSwiftSweets

**Comment by fpg1503** [comment]
Yeah, feel free! Thanks for the interest! 🎉

**Comment by MKGitHub** [comment]
Done! Please star my repo and share the word!
