### ISSUE TITLE
It seems need a long progressing after i open xcodegr8

### ISSUE THREAD

**Issue by AMEstudio** [fpg1503/MakeXcodeGr8Again#23]
every time i open xcodegr8 type some code and make a save(cmd+s or autosave) there must be a long progress (On the SSD need 3 to 5 minutes, ordinary hard disk need 20 to 25 minutes )
i have two mac,both of them has this problem.
my system is macOS 10.12

By the way, macOS 10.11 do not have this long progress on save.but have this problem when i create a new file(class xib...)

so.. way this problem?
is it a bug or necessary?
how can i deal with?

**Comment by chrisellsworth** [comment]
I think I had the same problem. Turns out there's a process called `tccd` that's working really had to verify the validity of your unsigned Xcode while sucking up all of your CPU. You can stop it from doing this by disabling Xcode's access to Contacts in the Security and Privacy settings.

**Comment by fpg1503** [comment]
Thanks for pointing it out, @chrisellsworth!
@AMEstudio does the solution above solve your problem?

**Comment by AMEstudio** [comment]
@chrisellsworth  @fpg1503 
At first, thank you for reply me.Thank you for your efforts on this plugin.

This is a great plugin, however I use other method to resign now.
this method is noticed from The author of XVim
here is an example.
https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md

Although I don't understand the principle, but I believe that you can try to put this principle to your plugin.
Let's make development easier : )

**Comment by fpg1503** [comment]
Woah! That's really awesome, I'll try to automate the XVim solution and add it to MakeXcodeGr8Again since it's working so well!

**Comment by AMEstudio** [comment]
@fpg1503 
That sounds good! Look forward to your efforts! Thank you very much : )

**Comment by fpg1503** [comment]
Moving this to #28
