### ISSUE TITLE
What's the roadmap for addressing the issues opened?

### ISSUE THREAD

**Issue by MKGitHub** [fpg1503/MakeXcodeGr8Again#26]
No updates for several months? ABANDONED project?

**Comment by fpg1503** [comment]
It's not abandoned I've just been really busy at my daily job with an upcoming release, I've started migrating it to allow multiple "greating" methods (aka unsigning/re-code signing) but that's on my personal Mac and I haven't pushed it. The basic functionality should be working fine, though, I've been using it on every new Xcode version.

Meanwhile I'll be more than happy to accept PRs :)

**Comment by fpg1503** [comment]
This issue will be closed because there hasn't been any activity for a few months. Feel free to [open a new one](https://github.com/fpg1503/MakeXcodeGr8Again/issues/newa) if you have any other questions 👍

PRs are still welcome 🚀
