### ISSUE TITLE
XcodeGr8 fails to launch

### ISSUE THREAD

**Issue by carlos-ivan-hernandez** [fpg1503/MakeXcodeGr8Again#32]
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/XcodeGr8.app.

Xcode 8.3.2

**Comment by alanhamlett** [comment]
Try this Terminal command instead:

`curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh`

You will get Alcatraz and WakaTime plugins also installed, but Xcode 8.3.2 will be unsigned.

**Comment by carlos-ivan-hernandez** [comment]
I ran:

`curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh -s copy` 

But the Alcatraz package manager doesn't show up in the Window menu.

**Comment by alanhamlett** [comment]
Running with `copy` creates a new Xcode app. Are you running `Xcode.app` or the new unsigned `XcodeWithPlugins.app`?

**Comment by carlos-ivan-hernandez** [comment]
XcodeWithPlugins.app`

**Comment by carlos-ivan-hernandez** [comment]
`XcodeWithPlugins.app`

**Comment by alanhamlett** [comment]
Just ran the same command and it worked for me... do you get an error message or other output?

**Comment by carlos-ivan-hernandez** [comment]
`XcodeWithPlugin.app` launches without any other output.

**Comment by alanhamlett** [comment]
That's strange, you could try copying `Xcode.app` to `XcodeOrig.app` then running without `-s copy`:

`curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh`

Also, to check the signer of the apps run these:
`codesign --display --verbose --verbose /Applications/Xcode.app`
`codesign --display --verbose --verbose /Applications/XcodeWithPlugins.app`

`XcodeWithPlugins.app` should say `Authority=XcodeSigner`.

**Comment by carlos-ivan-hernandez** [comment]
I got it to work. I copied `Xcode.app` and ran the command `curl -fsSL https://raw.githubusercontent.com/wakatime/xcode-wakatime/master/install.sh | sh`.

I think I clicked on "skip bundles" when I did it the first time... oops. Thank you for your help.
