### ISSUE TITLE
Add a plugin that disables app sumissions by default

### ISSUE THREAD

**Issue by fpg1503** [fpg1503/MakeXcodeGr8Again#4]
We don't want another 👻, right?

**Comment by fpg1503** [comment]
Some people have argued that's not necessary. I don't plan on making it mandatory but having it opt-out (rather than opt-in) looks like a good idea in this case (even though I'm normally against opt-outs).

**Comment by hammadzz** [comment]
I agree that this is something we should be able to opt-in on. I don't want to accidentally do an app submission using unsigned Xcode and end up in the shit storm if App Store trashes the app.

**Comment by fpg1503** [comment]
Thanks @insidegui! 🐥

**Comment by insidegui** [comment]
🐣
