### ISSUE TITLE
Add icon please

### ISSUE THREAD

**Issue by elton-mendes-movile** [fpg1503/MakeXcodeGr8Again#7]
![23-zwart](https://cloud.githubusercontent.com/assets/12896121/16327097/d2b6bdcc-39a2-11e6-901a-f045226dfd15.jpg)

**Comment by fpg1503** [comment]
I ran it through [VectorMagic](www.vectormagic.com) and did some tweaks on InkScape to make it look nicer/avoid using an image from the web: 

![yolo-vec](https://cloud.githubusercontent.com/assets/5491536/16341293/c5f835f6-3a02-11e6-8f70-d5732bfc8eb5.png)

I don't have Xcode 8 here so I'll probably just add it tonight. Do you think it should be the app icon or the new Xcode icon?

**Comment by eltonmendes** [comment]
*_*

**Comment by paulofierro** [comment]
I wanted something a little more visible and quickly made [this ridiculousness](https://dl.dropboxusercontent.com/u/4077080/MakeXcodeGr8/MakeXcodeGr8.png). [ICNS file here](https://dl.dropboxusercontent.com/u/4077080/MakeXcodeGr8/MakeXcodeGr8.icns).

Its intentionally quick and dirty to reflect the situation 😜

**Comment by fpg1503** [comment]
@paulofierro I've added your Icon, thanks for the contribution! 🎉 
@eltonmendes I'm still trying to figure out where to put this, I was thinking about adding it as the background of the view when YOLO mode is selected but it's a bit strange without any masks/blur on top so I'm working on that.
