### ISSUE TITLE
Make the implications clearer

### ISSUE THREAD

**Issue by marcelofabri** [fpg1503/MakeXcodeGr8Again#9]
IMO the README could have an explanation on why plugins were disabled by Apple (or at least why we think they disabled) and what the risks in "Use at your own risk" are.

Pointing out that some plugins can be replaced by extensions would be a plus, as pointing out that in an ideal world™, we'd have all APIs needed to create extensions for all existing plugins, so we should open radars.

![](https://blackpixel.com/writing/assets/2012_02_29_photo.png)

**Comment by fpg1503** [comment]
Woah, Github closed the issue automatically 😱.

Do you think the risks are clear enough or should I elucidate them more?

**Comment by marcelofabri** [comment]
👍 🎉
